# Site settings
title: scabla.net
email: goking@scabla.net
description: > # this means to ignore newlines until "baseurl:"
  21世紀はすかぶらもんの時代となる - goking
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scabla.net" # the base hostname & protocol for your site
twitter_username: goking
github_username:  goking

# Build settings
markdown: kramdown
